export default {
  PROFILE: require('../assets/profile_Icon.png'),
  BG_IMAGE: require('../assets/bg_image.jpeg'),
  BG: require('../assets/bg.jpeg'),
  CATERER: require('../assets/catere.jpeg'),
  DRIVER_LICENSE: require('../assets/Driver_license.jpeg'),
  LICENSE: require('../assets/license.jpeg'),
  MASTERCARD: require('../assets/masterCard.png'),
  RUPAY: require('../assets/Rupay.png'),
  SLIDER1: require('../assets/silder1.jpeg'),
  SILDER2: require('../assets/slider2.jpeg'),
  SLIDER3: require('../assets/slider3.jpeg'),
  SUCESS: require('../assets/sucess.jpeg'),
  VISA: require('../assets/visa.png'),
};
