export default {
  PROFILE: require('../assest/profile_Icon.png'),
  BG_IMAGE: require('../assest/bg_image.jpeg'),
  BG: require('../assest/bg.jpeg'),
  CATERER: require('../assest/catere.jpeg'),
  DRIVER_LICENSE: require('../assest/Driver_license.jpeg'),
  LICENSE: require('../assest/license.jpeg'),
  MASTERCARD: require('../assest/masterCard.png'),
  RUPAY: require('../assest/Rupay.png'),
  SLIDER1: require('../assest/silder1.jpeg'),
  SILDER2: require('../assest/slider2.jpeg'),
  SLIDER3: require('../assest/slider3.jpeg'),
  SUCESS: require('../assest/sucess.jpeg'),
  VISA: require('../assest/visa.png'),
};
